# Generated by Django 5.2 on 2025-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'ادمین ارشد'), ('admin', 'ادمین'), ('regular', 'مشتری معمولی'), ('vip', 'مشتری ویژه')], default='regular', max_length=15, verbose_name='نقش کاربر'),
        ),
    ]
