# Generated by Django 5.2 on 2025-05-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_is_active_cart_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total_price',
        ),
    ]
