# Generated by Django 5.2 on 2025-05-07 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(max_length=1200, verbose_name='توضیحات')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت محصول')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('new_price', models.PositiveIntegerField(default=0, verbose_name='قیمت با تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id', 'slug'], name='store_produ_id_2abda1_idx'), models.Index(fields=['name'], name='store_produ_name_5e57da_idx'), models.Index(fields=['-created_at'], name='store_produ_created_0fbdf8_idx')],
            },
        ),
    ]
